server:
  port: 33333

spring:
  mail:
    host: smtp.163.com #邮箱服务器地址
    username: 15638526132@163.com #
    password: zhang...1997 #
    default-encoding: UTF-8

mail:
  fromMail:
    addr: 15638526132@163.com #